server:
  port: 8072

spring:
  application:
    name: "gatewayserver"
        
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka/"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted  # ✅ allows /actuator/gateway/routes
  info:
    env:
      enabled: true

info:
  app:
    name: "gatewayserver"
    description: "Eazy Bank Gateway Server Application"
    version: "1.0.0"

logging:
  level:
    com:
      eazybytes:
        gatewayserver: DEBUG

# use above one before implement manual routes as well as for @Bean using RouteLocator


# server:
#   port: 8072

# spring:
#   application:
#     name: gatewayserver

#   config:
#     import: "optional:configserver:http://localhost:8071/"

#   cloud:
#     gateway:

#       discovery:
#         locator:
#           enabled: true
#           lowerCaseServiceId: true

#       routes:

#         - id: accounts
#           uri: lb://ACCOUNTS
#           predicates:
#             - Path=/eazybank/accounts/**
#           filters:
#             - RewritePath=/eazybank/accounts/(?<segment>.*), /$${segment}

#         - id: loans
#           uri: lb://LOANS
#           predicates:
#             - Path=/eazybank/loans/**
#           filters:
#             - RewritePath=/eazybank/loans/(?<segment>.*), /$${segment}

#         - id: cards
#           uri: lb://CARDS
#           predicates:
#             - Path=/eazybank/cards/**
#           filters:
#             - RewritePath=/eazybank/cards/(?<segment>.*), /$${segment}



